[placeholders.language]
type = "string"
prompt = "Language"
default = "typescript"
choices = ["typescript", "javascript"]

[conditional.'language == "typescript"']
ignore = ["frontend/main.js"]

[conditional.'language == "javascript"']
ignore = ["frontend/main.ts"]
